spring:
  application:
    name: backend

  output:
    ansi:
      enabled: ALWAYS # Options are: ALWAYS, DETECT, NEVER

#logging:
#  pattern:
#    console: "%blue(%d{HH:mm:ss}){blue} %green(%-5level) %green([%thread]){magenta} %black(%logger{36}){cyan} - %msg%n"